name: Build F3MB0Y APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential libffi-dev python3-dev automake autoconf libltdl-dev libtool pkg-config zlib1g-dev adb openjdk-17-jdk

      - name: Build with Buildozer
        uses: ArtemSerebriakov/buildozer-action@v1
        with:
          buildozer_version: master
          command: android debug
          repository_root: .

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: F3MB0Y-Payload
          path: bin/*.apk
          
