name: Build F3MB0Y APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install System Dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential libffi-dev python3-dev automake autoconf libltdl-dev libtool pkg-config zlib1g-dev adb openjdk-17-jdk zip unzip

      - name: Install Buildozer
        run: |
          pip install --upgrade pip
          pip install buildozer
          pip install cython

      - name: Build APK with Buildozer
        run: |
          # Kita paksa accept license biar gak nungguin input manual
          yes | buildozer -v android debug
        env:
          # Ini biar gak error pas build
          BUILDOZER_ALLOW_ORG_NAME_START_WITH_DIGIT: 1

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: F3MB0Y-Payload
          path: bin/*.apk
