name: Build F3MB0Y APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential libffi-dev python3-dev automake autoconf libltdl-dev libtool pkg-config zlib1g-dev adb openjdk-17-jdk

      - name: Build with Buildozer
        # Kita pakai action yang lebih stabil dan terupdate
        uses: Enteleform/buildozer-action@v1.2.2
        with:
          command: android debug
          buildozer_version: master

      - name: Upload APK
        # Update ke v4 biar gak kena omel GitHub lagi
        uses: actions/upload-artifact@v4
        with:
          name: F3MB0Y-Payload
          path: bin/*.apk
